CREATE DATABASE customer_behavior;
USE customer_behavior;

-- Q1. What is the total revenue and the perecentage of revenue generated by male vs female customers?
SELECT gender, ROUND(SUM(purchase_amount), 2) AS revenue,
ROUND(100 * SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer), 2) AS revenue_percentage
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer 
WHERE discount_applied = "Yes" AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC LIMIT 5;

-- Q4. Compare the avergae purchase amounts in all types of shipping
SELECT shipping_type, avg(purchase_amount) AS "Average Purchase Amount"
FROM customer 
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers. 

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue,
ROUND(100 * SUM(purchase_amount) /(SELECT SUM(purchase_amount) FROM customer), 2) AS revenue_percentage
FROM customer 
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
SELECT 
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment,
COUNT(*) as "Number of Customers",
ROUND(100 * COUNT(*) / (SELECT COUNT(*) FROM customer), 2) AS percentage
FROM customer
GROUP BY customer_segment;




