CREATE DATABASE customer_behavior;
USE customer_behavior;
SHOW TABLES;
DESCRIBE customer;
SELECT COUNT(*) FROM customer;
select * from customer limit 5;

-- Q1. What is the total revenue and the perecentage of revenue generated by male vs female customers?
SELECT gender, round(SUM(purchase_amount), 2) AS revenue,
round(100 * SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer), 2) AS revenue_percentage
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer 
where discount_applied = "Yes" and purchase_amount >= (select AVG(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc limit 5;

-- Q4. Compare the avergae purchase amounts in all types of shipping
select distinct shipping_type from customer;

select shipping_type, avg(purchase_amount) 
from customer 
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers. 
select distinct subscription_status from customer;

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue,
round(100 * SUM(purchase_amount) /(SELECT SUM(purchase_amount) FROM customer), 2) AS revenue_percentage
from customer 
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
Round(100 * Sum(Case When discount_applied = 'Yes' Then 1 Else 0 End)/Count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

select distinct previous_purchases from customer;

select 
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment,
count(*) as "Number of Customers",
round(100 * COUNT(*) / (SELECT COUNT(*) FROM customer), 2) AS percentage
from customer
group by customer_segment;




